wandb_version: 1

dataset:
  desc: null
  value: coco-stuff
model:
  desc: null
  value: Zhang_Cla_Lab
epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.0005
criterion:
  desc: null
  value: categorical_crossentropy
optimizer:
  desc: null
  value: Adam
train_num_max:
  desc: null
  value: 200
val_num_max:
  desc: null
  value: 20
pretrained:
  desc: null
  value: null
saved_weight_path:
  desc: null
  value: exp_Zhang_Cla_Lab_test/exp02.pt
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.38.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1710345794.94974
    t:
      1:
      - 1
      - 5
      - 11
      - 12
      - 49
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 11
      - 12
      - 49
      - 53
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.3
      6: 4.38.1
      8:
      - 2
      - 5
      13: linux-x86_64
